backend:
  name: git-gateway
  repo: grantballmer/purchase-productions
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "src/pages/services"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "gallery",
        }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Grid"
        name: "grid"
        widget: "list"
        fields:
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Band Name", name: "band", widget: "string" }
  - name: "podcast"
    label: "Podcast"
    folder: "src/pages/podcast"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "episode",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { name: path, label: Path }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Episode Number", name: "episode", widget: "string" }
      - { label: "Embed URL", name: "src", widget: "string" }

  - name: band
    label: Band
    folder: src/pages/roster
    create: true
    identifier_field: name
    fields:
      - { name: path, label: Path }
      - { name: name, label: Band Name }
      - { name: genre, label: Genre }
      - { name: body, label: Band Bio, widget: markdown }
      - { name: thumbnail, label: Roster Page Thumbnail, widget: image }
      - { name: banner, label: Band Page Banner, widget: image }
      - label: Social Media
        name: social
        widget: list
        fields:
          - { label: Spotify Link, name: spotify }
          - { label: Youtube Link, name: youtube }
          - { label: iTunes Link, name: itunes }
          - { label: Facebook Link, name: facebook }
          - { label: Instagram Link, name: instagram }
      - label: Management
        name: management
        widget: list
        allow_add: true
        fields:
          - { label: Position, name: position }
          - { label: Name, name: name }
          - { label: Email, name: email }
      - {
          label: Template Key,
          name: templateKey,
          widget: "hidden",
          default: "bandTemplate",
        }
